import { Router } from "express";
import { requireAuth, requireRole } from "../middleware/auth.js";
import { Application } from "../models/Application.js";

const withProgress = (application) => ({ ...application.toObject(), progress: Object.keys(application.formData ?? {}).length ? Math.min(100, Object.values(application.formData).filter((value) => value !== "" && value != null).length * 10) : 0 });

export const applicationRouter = Router();
applicationRouter.use(requireAuth);
applicationRouter.post("/", async (request, response, next) => { try { const { formId, formVersion, formData = {} } = request.body; if (!formId || !formVersion) return response.status(400).json({ error: "formId and formVersion are required." }); const application = await Application.create({ user: request.user.sub, formId, formVersion, formData }); response.status(201).json({ data: application }); } catch (error) { next(error); } });
applicationRouter.get("/", async (request, response, next) => { try { const applications = await Application.find({ user: request.user.sub }).sort({ updatedAt: -1 }); response.json({ data: applications.map(withProgress) }); } catch (error) { next(error); } });
applicationRouter.get("/:id", async (request, response, next) => { try { const application = await Application.findOne({ _id: request.params.id, user: request.user.sub }); if (!application) return response.status(404).json({ error: "Application not found." }); response.json({ data: withProgress(application) }); } catch (error) { next(error); } });
applicationRouter.put("/:id", async (request, response, next) => { try { const application = await Application.findOneAndUpdate({ _id: request.params.id, user: request.user.sub, status: { $in: ["DRAFT", "IN_PROGRESS"] } }, { $set: { formData: request.body.formData, status: "IN_PROGRESS" } }, { new: true }); if (!application) return response.status(404).json({ error: "Editable application not found." }); response.json({ data: application }); } catch (error) { next(error); } });
applicationRouter.delete("/:id", async (request, response, next) => { try { const application = await Application.findOneAndDelete({ _id: request.params.id, user: request.user.sub, status: "DRAFT" }); if (!application) return response.status(404).json({ error: "Draft not found." }); response.status(204).end(); } catch (error) { next(error); } });
applicationRouter.get("/review/queue", requireRole("ADMIN", "REVIEWER"), async (_request, response, next) => { try { const applications = await Application.find({ status: "SUBMITTED" }).sort({ updatedAt: 1 }); response.json({ data: applications }); } catch (error) { next(error); } });
applicationRouter.post("/:id/review", requireRole("ADMIN", "REVIEWER"), async (request, response, next) => { try { const { status, comment = "" } = request.body; if (! ["APPROVED", "REJECTED", "CHANGES_REQUESTED"].includes(status)) return response.status(400).json({ error: "Invalid review status." }); const application = await Application.findOneAndUpdate({ _id: request.params.id, status: "SUBMITTED" }, { $set: { status, reviewerComment: comment } }, { new: true }); if (!application) return response.status(404).json({ error: "Submitted application not found." }); response.json({ data: application }); } catch (error) { next(error); } });
applicationRouter.post("/:id/submit", async (request, response, next) => { try { const application = await Application.findOneAndUpdate({ _id: request.params.id, user: request.user.sub, status: { $in: ["DRAFT", "IN_PROGRESS"] } }, { $set: { status: "SUBMITTED" } }, { new: true }); if (!application) return response.status(404).json({ error: "Editable application not found." }); response.json({ data: application }); } catch (error) { next(error); } });
